"""
Generates src/assets/viewerHtml.js — a JS module exporting the full viewer
HTML as a string, with all Three.js scripts inlined from node_modules/three.

The WebView loads this string directly via source={{ html }} so no asset
file, no file:// URI and no network request is ever needed. This avoids
net::ERR_CLEARTEXT_NOT_PERMITTED and release-build asset resolution issues
on Android.

Run after `npm ci` (needs node_modules/three). Falls back to CDN download
if node_modules is missing. viewer.html itself is never modified.
"""
import json
import os
import sys
import time
import urllib.request

VIEWER_PATH = "src/assets/viewer.html"
OUTPUT_PATH = "src/assets/viewerHtml.js"

# (CDN script tag URL in viewer.html, local node_modules path)
SCRIPTS = [
    (
        "https://cdn.jsdelivr.net/npm/three@0.128.0/build/three.min.js",
        "node_modules/three/build/three.min.js",
    ),
    (
        "https://cdn.jsdelivr.net/npm/three@0.128.0/examples/js/controls/OrbitControls.js",
        "node_modules/three/examples/js/controls/OrbitControls.js",
    ),
    (
        "https://cdn.jsdelivr.net/npm/three@0.128.0/examples/js/loaders/GLTFLoader.js",
        "node_modules/three/examples/js/loaders/GLTFLoader.js",
    ),
    (
        "https://cdn.jsdelivr.net/npm/three@0.128.0/examples/js/loaders/OBJLoader.js",
        "node_modules/three/examples/js/loaders/OBJLoader.js",
    ),
    (
        "https://cdn.jsdelivr.net/npm/three@0.128.0/examples/js/loaders/STLLoader.js",
        "node_modules/three/examples/js/loaders/STLLoader.js",
    ),
]


def download(url, retries=4):
    for attempt in range(retries):
        try:
            req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
            with urllib.request.urlopen(req, timeout=60) as resp:
                return resp.read().decode("utf-8")
        except Exception as exc:
            if attempt < retries - 1:
                wait = 2 ** attempt
                print(f"  Retry {attempt + 2}/{retries} after {wait}s ({exc})")
                time.sleep(wait)
            else:
                raise RuntimeError(f"Download failed for {url}: {exc}")


with open(VIEWER_PATH, "r", encoding="utf-8") as f:
    html = f.read()

missing = []
for cdn_url, local_path in SCRIPTS:
    tag = f'<script src="{cdn_url}"></script>'
    if tag not in html:
        print(f"ERROR: tag not found in viewer.html: {cdn_url.split('/')[-1]}")
        missing.append(cdn_url)
        continue

    if os.path.exists(local_path):
        with open(local_path, "r", encoding="utf-8") as f:
            js = f.read()
        source = "node_modules"
    else:
        print(f"node_modules missing, downloading {cdn_url.split('/')[-1]}...")
        js = download(cdn_url)
        source = "CDN"

    html = html.replace(tag, f"<script>\n{js}\n</script>")
    print(f"Inlined {cdn_url.split('/')[-1]} ({len(js):,} chars, from {source})")

if missing:
    sys.exit(1)

if "cdn.jsdelivr.net" in html:
    print("ERROR: CDN references still present after inlining")
    sys.exit(1)

# json.dumps with ensure_ascii=True produces a valid JS string literal
# (all non-ASCII escaped, no raw U+2028/U+2029 issues).
literal = json.dumps(html, ensure_ascii=True)
module = (
    "// AUTO-GENERATED by scripts/bundle-threejs.py — DO NOT EDIT.\n"
    "// Source: src/assets/viewer.html (+ Three.js r128 inlined).\n"
    "// Regenerate with: python3 scripts/bundle-threejs.py\n"
    "/* eslint-disable */\n"
    f"export default {literal};\n"
)

with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
    f.write(module)

print(f"\nDone – {OUTPUT_PATH} written ({len(module):,} bytes, fully offline)")
